### ISSUE TITLE
It only accepts emails that are from certain domains

### ISSUE THREAD

**Issue by jvanbaarsen** [olivierlacan/orientation#107]
**The problem**
When creating a user the only accepted domain names are `(codeschool|pluralsight|smarterer).com`.

**Proposed fix**
Add a gem like https://github.com/hallelujah/valid_email to validate email addresses and see if they are valid.

If you want I can fix this.

**Comment by olivierlacan** [comment]
Derp. Can you submit a PR that just kills this check? Otherwise I'll fix it myself later today. 

Sorry about that. Oversight. :-)

**Comment by jvanbaarsen** [comment]
Yes will do!
