### ISSUE TITLE
Vendor is not included in asset pipeline, but bower_components is

### ISSUE THREAD

**Issue by johanandre** [olivierlacan/orientation#109]
I got errors from sprockets saying that js-files could not be found.
The solution is to change (in config/application.rb): 

```
config.assets.paths << Rails.root.join('bower_components')
```
to:
```
config.assets.paths << Rails.root.join('vendor')
```

**Comment by olivierlacan** [comment]
I'm honestly no Bower expert but @drewbarontini recommended running `bower install`. Did the install script not advise you to do that or to at least install npm/Bower to be able to do it?

**Comment by olivierlacan** [comment]
I would honestly prefer vendoring JS assets over relying on npm when installing/deploying.

**Comment by drewbarontini** [comment]
`bower install` will set up the `bower_components` directory, which should fix the issue.

**Comment by johanandre** [comment]
@olivierlacan Yes it did. But it installed in vendor/.

@drewbarontini No. Not in my setup.

**Comment by drewbarontini** [comment]
Interesting. Will look at that.

**Comment by olivierlacan** [comment]
@johanandre Good to know. Thanks for documenting the fix for people who might run into it. :-)
