### ISSUE TITLE
Show Me Rotten

### ISSUE THREAD

**Issue by toddheasley** [olivierlacan/orientation#111]
Is there a way to say “show me rotten” so that I can scan through and just tick “fresh” on stuff that’s good?

**Comment by olivierlacan** [comment]
There is not currently but I like this idea. Do you think a simple filter on the article index would be good?

Or would you want to see your rotten/stale articles only? The ones you either wrote or edited?

**Comment by toddheasley** [comment]
Filter that inverts the typical sorting would do it. Basically an "empathy" button for authors, who occasionally won't be using for reference but for clean out/up.

**Comment by olivierlacan** [comment]
@toddheasley Fixed via 6920b6925e8149a3c06806a94a2a246dd0005def

Looks like this:

![image](https://cloud.githubusercontent.com/assets/65950/6858954/fa6e29ae-d413-11e4-88bd-1de29919a321.png)

**Comment by olivierlacan** [comment]
As I post this I noticed the visual weight clash with the `New Article` button above. Fixing.

**Comment by olivierlacan** [comment]
Now looks like this: 

![image](https://cloud.githubusercontent.com/assets/65950/6859144/f8bceba2-d415-11e4-8f6f-56ad3921e0d9.png)
