### ISSUE TITLE
rake orientation:install fails if Gems are not previously installed

### ISSUE THREAD

**Issue by mclosson** [olivierlacan/orientation#112]
The installation step rake orientation:install fails if required Gems are not previously installed as is typically the case for a fresh Ruby install on a server.

```sh
~/orientation$ rake orientation:install
Could not find CFPropertyList-2.3.1 in any of the sources
Run `bundle install` to install missing gems.
```

This can easily be worked around by manually running bundle and then rerunning the rake task but is inconsistent with the current README.md documentation so I figured I'm adding an issue while going through the setup process.

**Comment by olivierlacan** [comment]
Weird: https://github.com/olivierlacan/orientation/blob/master/lib/tasks/orientation.rake#L7

**Comment by mclosson** [comment]
Hrmmm perhaps its an environmental issue, this is using bash + chruby + ruby-install, ruby 2.2.0 on FreeBSD 10.1 and ruby -e "system 'bundle install'" after the fact works fine.  I'll investigate and reopen it if I find out otherwise.
