### ISSUE TITLE
"No results"

### ISSUE THREAD

**Issue by olivierlacan** [olivierlacan/orientation#59]
We need to say when no results are available when searching otherwise it leaves a weird feeling that maybe search doesn't work right.

![image](https://cloud.githubusercontent.com/assets/65950/4016761/483a2826-2a38-11e4-9c7b-91c11ee02b36.png)

**Comment by fullsailor** [comment]
It could also prod the user to author a new article. Maybe providing a link to the new article page with the title prefilled.

**Comment by olivierlacan** [comment]
@fullsailor Yep, that's the idea.

**Comment by olivierlacan** [comment]
Fixed via 38b91d8e146a7dea3e5c580660264b3014e05213

**Comment by olivierlacan** [comment]
Looks like this:

![image](https://cloud.githubusercontent.com/assets/65950/6819357/291980a0-d2c0-11e4-8448-ed940de164fb.png)

And pre-fills the new article form:
![image](https://cloud.githubusercontent.com/assets/65950/6819362/37c95436-d2c0-11e4-96fc-8583b8155224.png)
