### ISSUE TITLE
How to handle long or nested guides?

### ISSUE THREAD

**Issue by adamfortuna** [olivierlacan/orientation#83]
I'm hoping to write a long guide for Campus with links to various parts groupings of posts. I started one here to test it out: http://orientation.codeschool.com/articles/campus-development-guide

How would something like this be handled? For this case, not every bullet is a link, aiming in readability and organization. Also, this could get a lot longer, making it look awkward on the front page sidebar.

Any thoughts on how to handle cases like this?

**Comment by olivierlacan** [comment]
Going to close this. This is has been solved by the new guides home page. 

![image](https://cloud.githubusercontent.com/assets/65950/6809957/1b4a57b8-d25e-11e4-96a0-7eaf02e3cb82.png)
